package DummyData;

import enums.itemType;

import models.item.ConsumableFood;
import models.item.Item;

import java.util.*;

public class consumables {

    private static final ConsumableFood[] DUMMY_CONSUMABLES = new ConsumableFood[]{
            c(1, "Salad Wortel Segar", 100, "Bahan: Wortel, Selada | Efek: Memulihkan 50 HP", 50, 0, 0, 0, "Wortel kaya akan Vitamin A yang sangat baik untuk kesehatan mata dan imunitas tubuh."),
            c(2, "Dada Ayam Panggang", 100, "Bahan: Dada Ayam, Lada Hitam | Efek: Memulihkan 100 HP, +10 Attack (3 turn)", 100, 0, 10, 0, "Dada ayam adalah sumber protein tanpa lemak yang ideal untuk memperbaiki sel otot yang rusak."),
            c(3, "Sup Tomat Merah", 100, "Bahan: Tomat, Bawang Putih | Efek: Memulihkan 40 HP & 20 Kekuatan", 40, 20, 0, 0, "Tomat mengandung likopen antioksidan yang melindungi sel dari kerusakan lingkungan."),
            c(4, "Oatmeal Pisang", 100, "Bahan: Gandum (Oat), Pisang | Efek: Memulihkan 30 Kekuatan, +Speed", 0, 30, 0, 0, "Gandum utuh memberikan energi lepas lambat sementara pisang kaya akan kalium untuk mencegah kram."),
            c(5, "Telur Rebus Sempurna", 100, "Bahan: Telur Ayam | Efek: Memulihkan 60 HP", 60, 0, 0, 0, "Telur adalah sumber protein lengkap yang mengandung asam amino esensial untuk fungsi otak."),
            c(6, "Brokoli Kukus", 100, "Bahan: Brokoli | Efek: Menyembuhkan status Poison", 0, 0, 0, 0, "Brokoli kaya akan serat dan vitamin C, sangat baik untuk detoksifikasi racun alami dalam tubuh."),
            c(7, "Steak Ikan Salmon", 100, "Bahan: Ikan Salmon, Lemon | Efek: Memulihkan 120 HP, +15 Defense", 120, 0, 0, 15, "Ikan salmon kaya akan asam lemak Omega-3 yang sangat penting untuk kesehatan jantung dan pembuluh darah."),
            c(8, "Kacang Almond Panggang", 100, "Bahan: Kacang Almond | Efek: Memulihkan 50 Kekuatan", 0, 50, 0, 0, "Almond mengandung lemak sehat dan vitamin E yang mendukung kesehatan kulit dari radiasi/wabah."),
            c(9, "Tumis Bayam Bawang Putih", 100, "Bahan: Bayam, Bawang Putih | Efek: Memulihkan 80 HP, +10 Defense", 80, 0, 0, 10, "Bayam adalah sumber zat besi yang luar biasa, mencegah anemia dan menjaga sel darah tetap sehat."),
            c(10, "Ubi Jalar Rebus", 100, "Bahan: Ubi Jalar | Efek: Memulihkan 70 HP & 30 Kekuatan", 70, 30, 0, 0, "Karbohidrat kompleks pada ubi jalar memberikan energi stabil tanpa melonjakkan gula darah."),
            c(11, "Yogurt Buah Beri", 100, "Bahan: Susu Fermentasi, Stroberi, Blueberry | Efek: Menyembuhkan segala Debuff", 0, 0, 0, 0, "Yogurt mengandung probiotik tinggi yang menjaga kesehatan pencernaan, inti dari imunitas tubuh."),
            c(12, "Lalapan Wortel Renyah", 100, "Bahan: Wortel, Selada | Efek: Memulihkan 50 HP", 50, 0, 0, 0, "Kombinasi wortel dan selada segar mentah mempertahankan enzim alami untuk metabolisme sel dan ketahanan imun."),
            c(13, "Tumis Ayam Lada Hitam Sehat", 100, "Bahan: Dada Ayam, Lada Hitam | Efek: Memulihkan 100 HP, +10 Attack (3 turn)", 100, 0, 10, 0, "Kandungan piperin pada lada hitam berpadu asam amino ayam mengoptimalkan penyerapan protein untuk pemulihan fisik."),
            c(14, "Saus Tomat Alami Murni", 100, "Bahan: Tomat, Bawang Putih | Efek: Memulihkan 40 HP & 20 Kekuatan", 40, 20, 0, 0, "Kombinasi alisin dari bawang putih dan zat likopen tomat membantu mengontrol tekanan darah dan sistem sirkulasi."),
            c(15, "Bubur Gandum Pisang Serat", 100, "Bahan: Gandum (Oat), Pisang | Efek: Memulihkan 30 Kekuatan, +Speed", 0, 30, 0, 0, "Serat beta-glukan dari gandum melancarkan pencernaan dan mengontrol pelepasan energi secara berkala selama laga."),
            c(16, "Telur Setengah Matang Bernutrisi", 100, "Bahan: Telur Ayam | Efek: Memulihkan 60 HP", 60, 0, 0, 0, "Kaya akan zat kolin dan lemak sehat tak jenuh, sangat baik untuk menutrisi sel-sel saraf otak."),
            c(17, "Cah Brokoli Bening", 100, "Bahan: Brokoli | Efek: Menyembuhkan status Poison", 0, 0, 0, 0, "Mengandung senyawa sulforafan tingkat tinggi yang membantu organ hati menetralisir racun dan zat asing."),
            c(18, "Salmon Panggang Air Lemon", 100, "Bahan: Ikan Salmon, Lemon | Efek: Memulihkan 120 HP, +15 Defense", 120, 0, 0, 15, "Kadar sitrus dari lemon meningkatkan bioavailabilitas nutrisi omega-3 salmon untuk melindungi kesehatan pembuluh darah."),
            c(19, "Susu Almond Murni Tanpa Gula", 100, "Bahan: Kacang Almond | Efek: Memulihkan 50 Kekuatan", 0, 50, 0, 0, "Kaya akan vitamin E dosis tinggi sebagai pelindung membran sel dari kerusakan oksidatif akibat radikal bebas."),
            c(20, "Sayur Bening Bayam Bawang", 100, "Bahan: Bayam, Bawang Putih | Efek: Memulihkan 80 HP, +10 Defense", 80, 0, 0, 10, "Zat besi non-heme yang berlimpah berpadu vitamin pembantu untuk memicu produksi hemoglobin baru pencegah anemia."),
            c(21, "Ubi Cilembu Panggang Alami", 100, "Bahan: Ubi Jalar | Efek: Memulihkan 70 HP & 30 Kekuatan", 70, 30, 0, 0, "Sumber makanan pokok alternatif berindeks glikemik rendah, aman dikonsumsi untuk menjaga berat badan ideal."),
            c(22, "Smoothie Beri Probiotik", 100, "Bahan: Susu Fermentasi, Stroberi, Blueberry | Efek: Menyembuhkan segala Debuff", 0, 0, 0, 0, "Antosianin dari beri berpadu kultur bakteri aktif untuk meredakan inflamasi sistem pencernaan secara menyeluruh."),
            c(23, "Wrap Sayur Wortel Segar", 100, "Bahan: Wortel, Selada | Efek: Memulihkan 50 HP", 50, 0, 0, 0, "Serat selulosa yang padat merangsang pertumbuhan bakteri baik dalam usus guna memperkuat benteng imunitas."),
            c(24, "Dada Ayam Suwir Pedas Hangat", 100, "Bahan: Dada Ayam, Lada Hitam | Efek: Memulihkan 100 HP, +10 Attack (3 turn)", 100, 0, 10, 0, "Membantu memenuhi kebutuhan protein harian tanpa risiko penumpukan kolesterol jahat (LDL) di dalam tubuh."),
            c(25, "Sup Krim Tomat Bawang", 100, "Bahan: Tomat, Bawang Putih | Efek: Memulihkan 40 HP & 20 Kekuatan", 40, 20, 0, 0, "Sup hangat berwujud cair yang mempercepat penyerapan zat antioksidan pencegah stres selular akibat kelelahan."),
            c(26, "Bar Energi Oat Pisang", 100, "Bahan: Gandum (Oat), Pisang | Efek: Memulihkan 30 Kekuatan, +Speed", 0, 30, 0, 0, "Potasium tinggi dari pisang menjaga regulasi osmotik sel tubuh agar tidak mudah mengalami dehidrasi jaringan."),
            c(27, "Telur Dadar Kukus Sehat", 100, "Bahan: Telur Ayam | Efek: Memulihkan 60 HP", 60, 0, 0, 0, "Metode masak tanpa minyak menjaga keutuhan struktur protein murni yang krusial untuk regenerasi jaringan terluka."),
            c(28, "Sup Brokoli Halus", 100, "Bahan: Brokoli | Efek: Menyembuhkan status Poison", 0, 0, 0, 0, "Mengandung vitamin K dan fitonutrien melimpah yang menunjang kesehatan persendian dan pemulihan sel internal."),
            c(29, "Fillet Salmon Saus Lemon", 100, "Bahan: Ikan Salmon, Lemon | Efek: Memulihkan 120 HP, +15 Defense", 120, 0, 0, 15, "Lemak sehat tak jenuh ganda (PUFA) membantu menurunkan kadar trigliserida berbahaya dalam sistem kardiovaskular."),
            c(30, "Granola Kacang Almond", 100, "Bahan: Kacang Almond | Efek: Memulihkan 50 Kekuatan", 0, 50, 0, 0, "Memberikan asupan kalsium dan magnesium nabati yang sangat dibutuhkan untuk menstabilkan sistem metabolisme."),
            c(31, "Salad Bayam Siram Bawang", 100, "Bahan: Bayam, Bawang Putih | Efek: Memulihkan 80 HP, +10 Defense", 80, 0, 0, 10, "Kandungan nitrat alami bayam meningkatkan efisiensi mitokondria sel dalam menghasilkan energi bertarung."),
            c(32, "Puree Ubi Jalar Lembut", 100, "Bahan: Ubi Jalar | Efek: Memulihkan 70 HP & 30 Kekuatan", 70, 30, 0, 0, "Makanan padat energi yang kaya beta-karoten untuk perbaikan jaringan kulit dan mempercepat penyembuhan luka fisik."),
            c(33, "Parfait Yogurt Buah Beri", 100, "Bahan: Susu Fermentasi, Stroberi, Blueberry | Efek: Menyembuhkan segala Debuff", 0, 0, 0, 0, "Kombinasi sinbiotik alami yang mengoptimalkan fungsi organ sekresi tubuh dalam mengeluarkan sisa zat beracun."),
            c(34, "Gado-Gado Wortel Mentah", 100, "Bahan: Wortel, Selada | Efek: Memulihkan 50 HP", 50, 0, 0, 0, "Hidangan tinggi serat bebas kolesterol untuk menjaga elastisitas usus dan kebersihan pembuluh darah."),
            c(35, "Steak Dada Ayam Lada Hitam", 100, "Bahan: Dada Ayam, Lada Hitam | Efek: Memulihkan 100 HP, +10 Attack (3 turn)", 100, 0, 10, 0, "Protein tinggi rendah lemak, fondasi utama pembangunan masa otot bebas cedera untuk petarung tangguh."),

            c(36, "Kentang Goreng Berbumbu", 100, "Bahan: Kentang, Minyak Jenuh, Garam Ekstra | Efek: +20 Attack, tetapi -10 Defense", 0, 0, 20, -10, "Digoreng dengan minyak yang digunakan berulang kali. Lemak trans di dalamnya dapat menyumbat pembuluh darah jantung."),
            c(37, "Burger Berlapis Keju Cair", 100, "Bahan: Roti Olahan, Daging Berlemak, Keju Imitasi | Efek: Memulihkan 150 HP, lalu HP berkurang 20/turn (3 turn)", 150, 0, 0, -20, "Sangat tinggi kalori dan lemak jenuh. Mengkonsumsinya memperlambat metabolisme dan memicu obesitas jangka panjang."),
            c(38, "Sosis Goreng MSG", 100, "Bahan: Sosis Olahan, MSG, Minyak | Efek: +30 Kekuatan, tetapi akurasi -20%", 0, 0, 30, -20, "Kandungan natrium dan MSG yang berlebihan dapat memicu dehidrasi dan tekanan darah tinggi mendadak."),
            c(39, "Permen Gula Kapas", 100, "Bahan: Gula Pasir, Pewarna Buatan | Efek: +50 Speed (1 turn), lalu -30 Speed (2 turn)", 0, 0, -10, 0, "Gula murni yang menyebabkan \"Sugar Rush\" (lonjakan energi seketika) yang selalu diikuti oleh rasa lelah ekstrem."),
            c(40, "Donat Gula Kental", 100, "Bahan: Tepung Terigu, Gula, Mentega | Efek: Memulihkan 80 HP, tetapi -10 Kekuatan", 80, 0, -10, 0, "Kombinasi tepung olahan dan gula tinggi yang meningkatkan risiko resistensi insulin dan diabetes."),
            c(41, "Mie Instan Kuah Asin", 100, "Bahan: Tepung Olahan, Pengawet, Bumbu Natrium Tinggi | Efek: Memulihkan 60 HP, terkena efek \"Haus\"", 60, 0, 0, -5, "Tinggi karbohidrat kosong dan pengawet. Sangat minim nutrisi mikro yang dibutuhkan tubuh untuk pulih dari luka."),
            c(42, "Ayam Goreng Tepung Ekstra", 100, "Bahan: Ayam (Kulit), Tepung, Minyak Jenuh | Efek: +25 Attack, tetapi terkena efek \"Slow\"", 0, 0, 25, -10, "Kalori sangat padat dari lemak jenuh. Menyebabkan penumpukan kolesterol jahat (LDL) jika dimakan terus menerus."),
            c(43, "Camilan Keripik Asin", 100, "Bahan: Kentang Olahan, Garam, Pengawet | Efek: +10 Kekuatan, Max HP berkurang 5% sementara", 0, -5, 10, 0, "Garam berlebih menahan cairan tubuh (retensi air), membebani kinerja ginjal secara drastis."),
            c(44, "Potato Wedges Deep-Fry", 100, "Bahan: Kentang, Minyak Jenuh, Garam Ekstra | Efek: +20 Attack, tetapi -10 Defense", 0, 0, 20, -10, "Penggorengan suhu tinggi memicu terbentuknya senyawa akrilamida yang bersifat merusak integritas sel sehat."),
            c(45, "Double Cheeseburger Junk Food", 100, "Bahan: Roti Olahan, Daging Berlemak, Keju Imitasi | Efek: Memulihkan 150 HP, lalu HP berkurang 20/turn (3 turn)", 150, 0, 0, -20, "Lemak jenuh ekstrem mengendap di dinding arteri koronaria, memicu penyempitan pembuluh darah (aterosklerosis)."),
            c(46, "Sosis Bakar Gurih Murahan", 100, "Bahan: Sosis Olahan, MSG, Minyak | Efek: +30 Kekuatan, tetapi akurasi -20%", 0, 0, 30, -20, "Zat pewarna kemerahan dan natrium tinggi pada daging olahan meningkatkan beban toksik akumulatif di tubuh."),
            c(47, "Permen Gulali Merah Muda", 100, "Bahan: Gula Pasir, Pewarna Buatan | Efek: +50 Speed (1 turn), lalu -30 Speed (2 turn)", 0, 0, -10, 0, "Pewarna sintetik non-pangan mengganggu fokus neurotransmiter otak dan merusak kondisi mikroflora usus."),
            c(48, "Donat Glaze Gula Pekat", 100, "Bahan: Tepung Terigu, Gula, Mentega | Efek: Memulihkan 80 HP, tetapi -10 Kekuatan", 80, 0, -10, 0, "Karbohidrat sederhana tanpa serat memaksa pankreas bekerja ekstra, meningkatkan risiko sindrom metabolik."),
            c(49, "Mie Instan Kuah Pedas Natrium", 100, "Bahan: Tepung Olahan, Pengawet, Bumbu Natrium Tinggi | Efek: Memulihkan 60 HP, terkena efek \"Haus\"", 60, 0, 0, -5, "Mengandung zat lilin pengawet yang memperlambat kinerja sistem pencernaan dalam menyerap nutrisi esensial."),
            c(50, "Ayam Goreng Krispi Kulit Tebal", 100, "Bahan: Ayam (Kulit), Tepung, Minyak Jenuh | Efek: +25 Attack, tetapi terkena efek \"Slow\"", 0, 0, 25, -10, "Lapisan tepung berminyak memicu penimbunan trigliserida bebas yang memicu perlemakan hati (fatty liver)."),
            c(51, "Keripik Kentang Kemasan Asin", 100, "Bahan: Kentang Olahan, Garam, Pengawet | Efek: +10 Kekuatan, Max HP berkurang 5% sementara", 0, -5, 10, 0, "Konsumsi garam kemasan tinggi secara konstan merusak nefron ginjal dan memicu hipertensi kronis."),
            c(52, "Keripik Kentang Balado Minyak", 100, "Bahan: Kentang, Minyak Jenuh, Garam Ekstra | Efek: +20 Attack, tetapi -10 Defense", 0, 0, 20, -10, "Kombinasi minyak jenuh teroksidasi dan zat pedas buatan memicu radang lambung (gastritis akut)."),
            c(53, "Burger Jumbo Keju Meleleh", 100, "Bahan: Roti Olahan, Daging Berlemak, Keju Imitasi | Efek: Memulihkan 150 HP, lalu HP berkurang 20/turn (3 turn)", 150, 0, 0, -20, "Makanan padat kalori kosong yang minim vitamin, memicu malnutrisi terselubung meskipun tubuh tampak gemuk."),
            c(54, "Sate Sosis Saus Mayones Berlemak", 100, "Bahan: Sosis Olahan, MSG, Minyak | Efek: +30 Kekuatan, tetapi akurasi -20%", 0, 0, 30, -20, "Lemak trans dari minyak goreng kualitas rendah merusak kestabilan kadar kolesterol baik (HDL) darah."),
            c(55, "Permen Jeli Warna-Warni", 100, "Bahan: Gula Pasir, Pewarna Buatan | Efek: +50 Speed (1 turn), lalu -30 Speed (2 turn)", 0, 0, -10, 0, "Mengandung pemanis buatan konsentrasi tinggi yang merusak enamel gigi dan memicu karies gigi parah."),
            c(56, "Donat Tabur Gula Bubuk", 100, "Bahan: Tepung Terigu, Gula, Mentega | Efek: Memulihkan 80 HP, tetapi -10 Kekuatan", 80, 0, -10, 0, "Tepung putih rafinasi cepat diubah tubuh menjadi glukosa darah kental yang mengganggu metabolisme energi."),
            c(57, "Mie Instan Goreng Bumbu Pekat", 100, "Bahan: Tepung Olahan, Pengawet, Bumbu Natrium Tinggi | Efek: Memulihkan 60 HP, terkena efek \"Haus\"", 60, 0, 0, -5, "Konsumsi jangka panjang tanpa sayuran dapat memicu sembelit kronis dan penumpukan zat aditif di usus."),
            c(58, "Ayam Pop Goreng Minyak Jenuh", 100, "Bahan: Ayam (Kulit), Tepung, Minyak Jenuh | Efek: +25 Attack, tetapi terkena efek \"Slow\"", 0, 0, 25, -10, "Menggunakan minyak jenuh yang dipanaskan berulang kali, memicu pelepasan radikal bebas perusak sel."),
            c(59, "Stik Kentang Asin Kemasan", 100, "Bahan: Kentang Olahan, Garam, Pengawet | Efek: +10 Kekuatan, Max HP berkurang 5% sementara", 0, -5, 10, 0, "Ketidakseimbangan natrium-kalium akibat camilan asin memicu gangguan retensi cairan di jaringan tubuh."),
            c(60, "Kentang Goreng Krispi Saus Keju", 100, "Bahan: Kentang, Minyak Jenuh, Garam Ekstra | Efek: +20 Attack, tetapi -10 Defense", 0, 0, 20, -10, "Saus keju imitasi mengandung banyak zat penstabil kimiawi yang membebani kinerja filtrasi organ ginjal."),
            c(61, "Triple Patty Burger Berminyak", 100, "Bahan: Roti Olahan, Daging Berlemak, Keju Imitasi | Efek: Memulihkan 150 HP, lalu HP berkurang 20/turn (3 turn)", 150, 0, 0, -20, "Porsi daging olahan berlemak tinggi yang melebihi ambang batas toleransi harian organ pencernaan manusia."),
            c(62, "Sosis Goreng Tepung (Corn Dog)", 100, "Bahan: Sosis Olahan, MSG, Minyak | Efek: +30 Kekuatan, tetapi akurasi -20%", 0, 0, 30, -20, "Lapisan adonan tepung tebal yang digoreng kering mengikat kandungan zat karsinogenik berbahaya."),
            c(63, "Kembang Gula Pelangi", 100, "Bahan: Gula Pasir, Pewarna Buatan | Efek: +50 Speed (1 turn), lalu -30 Speed (2 turn)", 0, 0, -10, 0, "Menyebabkan kelelahan kelenjar adrenal akibat fluktuasi hormon insulin yang dipaksa melonjak drastis."),
            c(64, "Donat Cokelat Meses Klasik", 100, "Bahan: Tepung Terigu, Gula, Mentega | Efek: Memulihkan 80 HP, tetapi -10 Kekuatan", 80, 0, -10, 0, "Kombinasi mentega trans tinggi dan butiran cokelat manis memicu risiko peradangan kronis di tingkat sel."),
            c(65, "Mie Instan Cup Praktis", 100, "Bahan: Tepung Olahan, Pengawet, Bumbu Natrium Tinggi | Efek: Memulihkan 60 HP, terkena efek \"Haus\"", 60, 0, 0, -5, "Kemasan plastik/styrofoam yang terpapar kuah panas berpotensi melepaskan mikroplastik pemicu kanker."),
            c(66, "Sayap Ayam Goreng Tepung Madu", 100, "Bahan: Ayam (Kulit), Tepung, Minyak Jenuh | Efek: +25 Attack, tetapi terkena efek \"Slow\"", 0, 0, 25, -10, "Glukosa cair pekat menyelimuti lemak jenuh kulit ayam, kombinasi terburuk bagi elastisitas pembuluh darah."),
            c(67, "Keripik Kentang Panggang Asin Ekstra", 100, "Bahan: Kentang Olahan, Garam, Pengawet | Efek: +10 Kekuatan, Max HP berkurang 5% sementara", 0, -5, 10, 0, "Walau dipanggang, kadar garam yang terlalu pekat tetap memicu lonjakan tekanan darah (hipertensi)."),
            c(68, "Kentang Goreng Ulir Mentega", 100, "Bahan: Kentang, Minyak Jenuh, Garam Ekstra | Efek: +20 Attack, tetapi -10 Defense", 0, 0, 20, -10, "Siraman mentega cair jenuh melipatgandakan kadar kalori kosong yang cepat menimbun jaringan adiposa."),
            c(69, "Slidder Burger Keju Asin", 100, "Bahan: Roti Olahan, Daging Berlemak, Keju Imitasi | Efek: Memulihkan 150 HP, lalu HP berkurang 20/turn (3 turn)", 150, 0, 0, -20, "Kalori tinggi dalam porsi kecil yang merusak sinyal rasa kenyang alami di hipotalamus otak."),
            c(70, "Sosis Gulung Mie Goreng", 100, "Bahan: Sosis Olahan, MSG, Minyak | Efek: +30 Kekuatan, tetapi akurasi -20%", 0, 0, 30, -20, "Penggabungan dua jenis karbohidrat olahan rafinasi dan sodium tinggi, mempercepat penuaan dini sel tubuh."),

            c(71, "Jus Wortel Murni", 100, "Bahan: Wortel, Air | Efek: Memulihkan 40 Kekuatan", 0, 40, 0, 0, "Sari wortel murni yang langsung diserap tubuh untuk menutrisi sel mata dan mencerahkan pandangan."),
            c(72, "Air Kelapa Segar", 100, "Bahan: Air Kelapa Muda | Efek: Menyembuhkan Dehidrasi & 50 HP", 50, 0, 0, 0, "Isotonik alami terbaik. Air kelapa mengembalikan keseimbangan elektrolit tubuh lebih cepat dari air biasa."),
            c(73, "Teh Hijau Hangat", 100, "Bahan: Daun Teh Hijau, Air Panas | Efek: Mempercepat regenerasi Kekuatan", 0, 0, 0, 0, "Teh hijau mengandung katekin, antioksidan yang membakar kalori dan melindungi sel dari mutasi penyakit."),
            c(74, "Jus Jeruk Peras", 100, "Bahan: Jeruk Segar | Efek: Memulihkan 60 HP, kebal penyakit 1 turn", 60, 0, 0, 0, "Kaya akan Vitamin C dosis tinggi yang bertindak sebagai perisai alami melawan patogen dan virus udara."),
            c(75, "Susu Sapi Murni", 100, "Bahan: Susu Sapi Segar | Efek: Memulihkan 70 HP & 20 Kekuatan", 70, 20, 0, 0, "Susu kaya akan Kalsium dan Vitamin D, fondasi utama untuk kepadatan tulang dan kekuatan kerangka."),
            c(76, "Seduhan Jahe Madu", 100, "Bahan: Jahe, Madu Alami | Efek: Menyembuhkan status \"Kedinginan/Freeze\"", 0, 0, 0, 0, "Jahe menghangatkan peredaran darah, sementara madu adalah antibakteri alami untuk meredakan radang."),
            c(77, "Jus Apel Merah", 100, "Bahan: Apel Merah | Efek: Memulihkan 50 HP", 50, 0, 0, 0, "Apel kaya akan pektin (serat larut) yang mengontrol kadar gula darah dan menyehatkan usus."),
            c(78, "Air Mineral Pegunungan", 100, "Bahan: Air Murni | Efek: Memulihkan 30 HP & 30 Kekuatan", 30, 30, 0, 0, "Air tanpa zat tambahan. Esensial untuk fungsi ginjal dan memastikan hidrasi darah tetap optimal untuk bertarung."),
            c(79, "Sari Wortel Dingin Murni", 100, "Bahan: Wortel, Air | Efek: Memulihkan 40 Kekuatan", 0, 40, 0, 0, "Ekstrak wortel cair tanpa ampas memudahkan usus menyerap karotenoid pencegah rabun senja."),
            c(80, "Air Kelapa Hijau Alami", 100, "Bahan: Air Kelapa Muda | Efek: Menyembuhkan Dehidrasi & 50 HP", 50, 0, 0, 0, "Kaya kandungan kalium murni untuk mengoptimalkan hantaran impuls saraf ke otot motorik tubuh."),
            c(81, "Seduhan Matcha Tanpa Gula", 100, "Bahan: Daun Teh Hijau, Air Panas | Efek: Mempercepat regenerasi Kekuatan", 0, 0, 0, 0, "Zat antioksidan EGCG tingkat tinggi membantu sel menangkal mutasi oksidatif yang berbahaya."),
            c(82, "Jus Jeruk Peras Alami Murni", 100, "Bahan: Jeruk Segar | Efek: Memulihkan 60 HP, kebal penyakit 1 turn", 60, 0, 0, 0, "Kandungan fitonutrien aktif citrus menstimulasi pembentukan leukosit sebagai agen imun pertahanan."),
            c(83, "Susu Sapi Pasteurisasi Murni", 100, "Bahan: Susu Sapi Segar | Efek: Memulihkan 70 HP & 20 Kekuatan", 70, 20, 0, 0, "Melalui pemanasan suhu tepat, bakteri merugikan lenyap tanpa merusak struktur bioavailabilitas kalsium tulang."),
            c(84, "Wedang Jahe Madu Hangat", 100, "Bahan: Jahe, Madu Alami | Efek: Menyembuhkan status \"Kedinginan/Freeze\"", 0, 0, 0, 0, "Senyawa gingerol jahe meredakan nyeri otot pasca-laga dan mengurangi inflamasi saluran napas."),
            c(85, "Sari Apel Merah Peras", 100, "Bahan: Apel Merah | Efek: Memulihkan 50 HP", 50, 0, 0, 0, "Kandungan zat quercetin bertindak sebagai agen antiinflamasi alami untuk melindungi fungsi paru-paru."),
            c(86, "Air Alkali Pegunungan Alami", 100, "Bahan: Air Murni | Efek: Memulihkan 30 HP & 30 Kekuatan", 30, 30, 0, 0, "Memiliki tingkat pH seimbang untuk membantu menetralkan tumpukan asam laktat di otot yang memicu pegal."),
            c(87, "Smoothie Wortel Madu Sehat", 100, "Bahan: Wortel, Air | Efek: Memulihkan 40 Kekuatan", 0, 40, 0, 0, "Kombinasi zat gizi mikro membantu pemeliharaan dan regenerasi sel epitel kulit dari ancaman luar."),
            c(88, "Es Air Kelapa Muda Murni", 100, "Bahan: Air Kelapa Muda | Efek: Menyembuhkan Dehidrasi & 50 HP", 50, 0, 0, 0, "Efektif membersihkan saluran kemih secara alami serta membuang sisa endapan natrium yang berlebih."),
            c(89, "Teh Hijau Seduh Daun Utuh", 100, "Bahan: Daun Teh Hijau, Air Panas | Efek: Mempercepat regenerasi Kekuatan", 0, 0, 0, 0, "Memberikan asupan polifenol alami untuk merawat elastisitas dinding pembuluh darah di seluruh tubuh."),
            c(90, "Sari Jeruk Nipis Hangat", 100, "Bahan: Jeruk Segar | Efek: Memulihkan 60 HP, kebal penyakit 1 turn", 60, 0, 0, 0, "Meskipun asam di mulut, sifat alkalizing pasca-cerna membantu menstabilkan tingkat keasaman lambung."),
            c(91, "Susu Sapi UHT Plain", 100, "Bahan: Susu Sapi Segar | Efek: Memulihkan 70 HP & 20 Kekuatan", 70, 20, 0, 0, "Sumber protein kasein yang diserap bertahap, memberikan suplai asam amino berkala untuk perbaikan jaringan."),
            c(92, "Teh Jahe Madu Rempah", 100, "Bahan: Jahe, Madu Alami | Efek: Menyembuhkan status \"Kedinginan/Freeze\"", 0, 0, 0, 0, "Melancarkan aliran sirkulasi darah perifer, meredakan mual, dan menghangatkan organ dalam tubuh."),
            c(93, "Cold-Pressed Jus Apel", 100, "Bahan: Apel Merah | Efek: Memulihkan 50 HP", 50, 0, 0, 0, "Metode perasan dingin mempertahankan integritas enzim pembantu pencernaan dan vitamin sensitif panas."),
            c(94, "Air Mineral Kemasan Steril", 100, "Bahan: Air Murni | Efek: Memulihkan 30 HP & 30 Kekuatan", 30, 30, 0, 0, "Menjaga stabilitas volume plasma darah agar distribusi oksigen ke sel otot berjalan tanpa hambatan."),
            c(95, "Nektar Wortel Segar", 100, "Bahan: Wortel, Air | Efek: Memulihkan 40 Kekuatan", 0, 40, 0, 0, "Membantu mengurangi risiko degradasi makula dini pada mata akibat paparan kelelahan bertarung."),
            c(96, "Air Kelapa Pemulih Ion", 100, "Bahan: Air Kelapa Muda | Efek: Menyembuhkan Dehidrasi & 50 HP", 50, 0, 0, 0, "Keseimbangan ionik alaminya mencegah terjadinya kram otot ekstrem akibat kelelahan atau panas berlebih."),
            c(97, "Infusi Teh Hijau Melati", 100, "Bahan: Daun Teh Hijau, Air Panas | Efek: Mempercepat regenerasi Kekuatan", 0, 0, 0, 0, "L-teanin di dalamnya merilekskan ketegangan saraf otak tanpa menimbulkan efek kantuk yang menurunkan fokus."),

            c(106, "Minuman Bersoda Manis", 100, "Bahan: Air Karbonasi, Sirup Jagung (HFCS), Pewarna | Efek: +30 Speed, mengurangi Max Kekuatan 10%", 0, -10, 0, 0, "Kandungan gula sintetis cairnya langsung membanjiri hati, meningkatkan risiko perlemakan hati dan kerusakan gigi."),
            c(107, "Minuman Berenergi Sintetis", 100, "Bahan: Kafein Ekstra, Taurin, Pemanis Buatan | Efek: Memulihkan 100 Kekuatan, lalu HP drop 30%", -30, 100, 0, 0, "Memacu jantung melebihi batas aman. Konsumsi berlebih bisa memicu aritmia (gangguan irama jantung)."),
            c(108, "Es Kopi Gula Aren Ganda", 100, "Bahan: Ekstrak Kopi, Krimer Nabati, Gula Aren Berlebih | Efek: +20 Attack, kebal efek \"Sleep\", tetapi akurasi -15%", 0, 0, 20, -15, "Krimer nabati tinggi lemak trans dipadu gula menyebabkan lonjakan insulin tajam yang merusak sensitivitas sel."),
            c(109, "Sirup Merah Buatan", 100, "Bahan: Air, Pewarna Karmin Sintetis, Pemanis | Efek: Memulihkan 40 HP, terkena status \"Poison\" 1 turn", 40, 0, 0, -5, "Pewarna buatan murah sering kali tidak dapat dicerna baik oleh ginjal, menjadi beban toksik jika diminum rutin."),
            c(110, "Jus Kotak Kemasan Manis", 100, "Bahan: Konsentrat Buah (Sedikit), Gula Tambahan Ekstra | Efek: Memulihkan 20 HP, -5 Defense", 20, 0, 0, -5, "Sering dikira sehat padahal serat buahnya sudah hancur dan diganti dengan pemanis buatan penimbun lemak."),
            c(111, "Minuman Boba Ekstra Manis", 100, "Bahan: Tepung Tapioka, Teh Hitam, Susu Kental Manis | Efek: +15 Kekuatan, -10 Speed", 0, 0, 15, -10, "Kaya akan kalori kosong. Boba (tapioka) dan susu kental manis menyumbang tumpukan karbohidrat tanpa nutrisi pelengkap."),
            c(112, "Alkohol Sulingan Kasar", 100, "Bahan: Fermentasi Buah Busuk/Gandum | Efek: +40 Attack, Akurasi -50%, terkena efek \"Confusion\"", 0, 0, 40, -20, "Meracuni fungsi otak dan merusak liver (hati) secara permanen jika menjadi kebiasaan."),
            c(113, "Cola Bersoda Hitam Pekat", 100, "Bahan: Air Karbonasi, Sirup Jagung (HFCS), Pewarna | Efek: +30 Speed, mengurangi Max Kekuatan 10%", 0, -10, 0, 0, "Kandungan asam fosfat tinggi mengikat kalsium tubuh, memicu pengeroposan kepadatan tulang (osteoporosis)."),
            c(114, "Minuman Stamina Berenergi Tinggi", 100, "Bahan: Kafein Ekstra, Taurin, Pemanis Buatan | Efek: Memulihkan 100 Kekuatan, lalu HP drop 30%", -30, 100, 0, 0, "Memaksa kelenjar adrenal bekerja di luar batas, memicu kelelahan kronis jangka panjang (adrenal fatigue)."),
            c(115, "Kopi Susu Gula Aren Kekinian", 100, "Bahan: Ekstrak Kopi, Krimer Nabati, Gula Aren Berlebih | Efek: +20 Attack, kebal efek \"Sleep\", tetapi akurasi -15%", 0, 0, 20, -15, "Kombinasi kalori cair tinggi dari gula aren dan krimer mempercepat pengendapan kolesterol jahat di pembuluh darah."),
            c(116, "Sirup Rasa Stroberi Buatan", 100, "Bahan: Air, Pewarna Karmin Sintetis, Pemanis | Efek: Memulihkan 40 HP, terkena status \"Poison\" 1 turn", 40, 0, 0, -5, "Gula biang dan esens kimiawi tanpa buah asli, hanya memberikan beban filtrasi ekstra pada organ nefron ginjal."),
            c(117, "Jus Buah Kemasan Kotak Manis", 100, "Bahan: Konsentrat Buah (Sedikit), Gula Tambahan Ekstra | Efek: Memulihkan 20 HP, -5 Defense", 20, 0, 0, -5, "Proses pasteurisasi suhu ekstrem mematikan vitamin asli, menyisakan fruktosa cair penimbun lemak perut."),
            c(118, "Bubble Tea Boba Gula Aren", 100, "Bahan: Tepung Tapioka, Teh Hitam, Susu Kental Manis | Efek: +15 Kekuatan, -10 Speed", 0, 0, 15, -10, "Tekstur boba tapioka yang kenyal sulit dicerna lambung jika dikonsumsi berlebih tanpa adanya asupan serat makanan."),
            c(119, "Alkohol Oplosan Kadar Tinggi", 100, "Bahan: Fermentasi Buah Busuk/Gandum | Efek: +40 Attack, Akurasi -50%, terkena efek \"Confusion\"", 0, 0, 40, -20, "Menghancurkan membran pelindung lambung dan menyebabkan kematian sel hepatosit hati secara masif."),
            c(120, "Soda Rasa Buah Sintetis", 100, "Bahan: Air Karbonasi, Sirup Jagung (HFCS), Pewarna | Efek: +30 Speed, mengurangi Max Kekuatan 10%", 0, -10, 0, 0, "Kandungan kalori kosong mengacaukan regulasi hormon ghrelin, memicu perilaku makan berlebih (overeating)."),
            c(121, "Minuman Booster Energi Instan", 100, "Bahan: Kafein Ekstra, Taurin, Pemanis Buatan | Efek: Memulihkan 100 Kekuatan, lalu HP drop 30%", -30, 100, 0, 0, "Pemanis buatan kimia dapat merusak mikrobioma usus sehat, mengganggu stabilitas kekebalan tubuh."),
            c(122, "Es Kopi Krimer Gula Ekstra", 100, "Bahan: Ekstrak Kopi, Krimer Nabati, Gula Aren Berlebih | Efek: +20 Attack, kebal efek \"Sleep\", tetapi akurasi -15%", 0, 0, 20, -15, "Mengakibatkan fenomena lonjakan energi sesaat yang selalu diakhiri dengan penurunan stamina drastis (energy crash)."),
            c(123, "Sirup Merah Delima Buatan", 100, "Bahan: Air, Pewarna Karmin Sintetis, Pemanis | Efek: Memulihkan 40 HP, terkena status \"Poison\" 1 turn", 40, 0, 0, -5, "Tingginya konsentrasi zat aditif pengawet berisiko memicu peradangan mukosa usus halus."),
            c(124, "Minuman Rasa Buah Kemasan", 100, "Bahan: Konsentrat Buah (Sedikit), Gula Tambahan Ekstra | Efek: Memulihkan 20 HP, -5 Defense", 20, 0, 0, -5, "Mengandung pemanis sintetis murah yang mempercepat penumpukan asam urat dan merusak persendian."),
            c(125, "Minuman Boba Susu Karamel", 100, "Bahan: Tepung Tapioka, Teh Hitam, Susu Kental Manis | Efek: +15 Kekuatan, -10 Speed", 0, 0, 15, -10, "Gula kental karamel memicu glycation, proses perusakan struktur kolagen jaringan tubuh akibat gula berlebih."),
            c(126, "Arak Sulingan Tradisional Kasar", 100, "Bahan: Fermentasi Buah Busuk/Gandum | Efek: +40 Attack, Akurasi -50%, terkena efek \"Confusion\"", 0, 0, 40, -20, "Etanol berkadar tidak terkontrol mengikis dinding lambung dan melumpuhkan saraf koordinasi motorik otak."),
            c(127, "Soda Bening Karbonasi Manis", 100, "Bahan: Air Karbonasi, Sirup Jagung (HFCS), Pewarna | Efek: +30 Speed, mengurangi Max Kekuatan 10%", 0, -10, 0, 0, "Karbonasi buatan menciptakan sensasi kembung semu yang mengikis nafsu makan terhadap makanan bergizi."),
            c(128, "Minuman Kaleng Berkafein Tinggi", 100, "Bahan: Kafein Ekstra, Taurin, Pemanis Buatan | Efek: Memulihkan 100 Kekuatan, lalu HP drop 30%", -30, 100, 0, 0, "Memaksa jantung memompa aliran darah terlalu cepat, meningkatkan risiko serangan stroke mendadak."),
            c(129, "Kopi Instan 3-in-1 Super Manis", 100, "Bahan: Ekstrak Kopi, Krimer Nabati, Gula Aren Berlebih | Efek: +20 Attack, kebal efek \"Sleep\", tetapi akurasi -15%", 0, 0, 20, -15, "Krimer hidrogenasi di dalamnya meningkatkan kadar kolesterol LDL (jahat) secara signifikan dalam darah."),
            c(130, "Minuman Sirup Es Lilin Pewarna", 100, "Bahan: Air, Pewarna Karmin Sintetis, Pemanis | Efek: Memulihkan 40 HP, terkena status \"Poison\" 1 turn", 40, 0, 0, -5, "Menggunakan zat pewarna non-standar yang mengendap di dalam ginjal, memicu pembentukan batu ginjal."),
            c(131, "Nektar Buah Kemasan Manis", 100, "Bahan: Konsentrat Buah (Sedikit), Gula Tambahan Ekstra | Efek: Memulihkan 20 HP, -5 Defense", 20, 0, 0, -5, "Mengandung sirup glukosa konsentrasi tinggi yang memicu obesitas abdominal (buncit) tidak sehat."),
            c(132, "Boba Milk Tea Velvet", 100, "Bahan: Tepung Tapioka, Teh Hitam, Susu Kental Manis | Efek: +15 Kekuatan, -10 Speed", 0, 0, 15, -10, "Tingginya kalori kosong dari kental manis mempercepat timbulnya gejala resistensi insulin tubuh."),
            c(133, "Minuman Keras Sulingan Ilegal", 100, "Bahan: Fermentasi Buah Busuk/Gandum | Efek: +40 Attack, Akurasi -50%, terkena efek \"Confusion\"", 0, 0, 40, -20, "Sifat toksisitas alkohol merusak barier darah-otak, memicu penurunan daya ingat secara permanen."),
            c(134, "Air Soda Beraroma Manis", 100, "Bahan: Air Karbonasi, Sirup Jagung (HFCS), Pewarna | Efek: +30 Speed, mengurangi Max Kekuatan 10%", 0, -10, 0, 0, "Menghancurkan ekosistem bakteri baik usus, menurunkan imunitas alami tubuh terhadap penyakit infeksi."),
            c(135, "Shot Energi Sintetis Ekstrem", 100, "Bahan: Kafein Ekstra, Taurin, Pemanis Buatan | Efek: Memulihkan 100 Kekuatan, lalu HP drop 30%", -30, 100, 0, 0, "Menyebabkan dehidrasi seluler berat dan ketidakseimbangan elektrolit jantung pemicu pingsan mendadak."),
            c(136, "Kopi Latte Instan Manis Pekat", 100, "Bahan: Ekstrak Kopi, Krimer Nabati, Gula Aren Berlebih | Efek: +20 Attack, kebal efek \"Sleep\", tetapi akurasi -15%", 0, 0, 20, -15, "Konsumsi rutin harian mengacaukan kadar glukosa darah puasa, gerbang utama menuju diabetes melitus tipe 2."),
            c(137, "Sirup Koktail Buah Buatan", 100, "Bahan: Air, Pewarna Karmin Sintetis, Pemanis | Efek: Memulihkan 40 HP, terkena status \"Poison\" 1 turn", 40, 0, 0, -5, "Pemanis buatan dosis tinggi mengacaukan respon metabolik alami tubuh terhadap asupan kalori asli makanan."),
            c(138, "Jus Jeruk Kotak Pengawet", 100, "Bahan: Konsentrat Buah (Sedikit), Gula Tambahan Ekstra | Efek: Memulihkan 20 HP, -5 Defense", 20, 0, 0, -5, "Penambahan zat natrium benzoat sebagai pengawet berlebih memicu reaksi radang seluler di pembuluh darah."),
            c(139, "Es Boba Matcha Manis Pekat", 100, "Bahan: Tepung Tapioka, Teh Hitam, Susu Kental Manis | Efek: +15 Kekuatan, -10 Speed", 0, 0, 15, -10, "Manfaat antioksidan teh hijau tertutup sepenuhnya oleh tumpukan kalori jenuh boba dan susu kental manis."),
            c(140, "Alkohol Fermentasi Murahan", 100, "Bahan: Fermentasi Buah Busuk/Gandum | Efek: +40 Attack, Akurasi -50%, terkena efek \"Confusion\"", 0, 0, 40, -20, "Menyebabkan kerusakan organ hati stadium lanjut, memicu sirosis biliaris yang fatal bagi kesehatan."),
    };

    private static final HashMap<Integer, Item> CONSUMABLE_MAP = initializeMap();

    private static HashMap<Integer, Item> initializeMap() {
        HashMap<Integer, Item> map = new HashMap<>();
        for (ConsumableFood food : DUMMY_CONSUMABLES) {
            map.put(food.getIdItem(), food);
        }
        return map;
    }

    private static ConsumableFood c(int id, String nama, int hargaJual, String deskripsi,
                                     int healHpAmount, int healMpAmount, int strBuff, int defBuff, String infoGiziSDG) {
        return new ConsumableFood(id, nama, hargaJual, deskripsi, itemType.CONSUMABLE, healHpAmount, healMpAmount, strBuff, defBuff, infoGiziSDG);
    }

    public static List<ConsumableFood> getDummyConsumables() {
        return List.of(DUMMY_CONSUMABLES);
    }

    public static HashMap<Integer, Item> getDummyConsumablesMap() {
        return CONSUMABLE_MAP;
    }
}
