package DummyData;

import enums.itemType;
import models.item.Inqredients;
import models.item.Item;

import java.util.*;

public class inqredients {

    private static final Inqredients[] DUMMY_INGREDIENTS = new Inqredients[]{
            i(1, "Serat Gandum Kering", 50, "Bahan dasar kain zirah ringan."),
            i(2, "Air Keruh", 40, "Digunakan dalam penyulingan awal."),
            i(3, "Kayu Lapuk", 45, "Gagang senjata tingkat rendah."),
            i(4, "Batu Tumpul", 35, "Penempaan senjata tumpul."),
            i(5, "Lendir Slime Biasa", 60, "Lem atau perekat material."),
            i(6, "Kain Rombeng", 30, "Bahan crafting perban dasar."),
            i(7, "Besi Karatan", 75, "Dilebur menjadi pelat baja murah."),
            i(8, "Tali Rami", 40, "Mengikat komponen senjata."),
            i(9, "Tulang Rapuh", 55, "Pembuatan jarum atau pisau kecil."),
            i(10, "Daun Obat Kering", 70, "Campuran ramuan penyembuh awal."),
            i(11, "Pecahan Kaca", 35, "Mata panah tajam namun rapuh."),
            i(12, "Bulu Burung Hama", 40, "Penstabil anak panah (fletching)."),
            i(13, "Getah Pohon Cemara", 80, "Bahan anti-air untuk armor."),
            i(14, "Kulit Tikus Selokan", 65, "Pelapis sarung tangan ringan."),
            i(15, "Taring Goblin", 90, "Mata pisau belati pemula."),
            i(16, "Tanah Liat", 45, "Cetakan leburan logam."),
            i(17, "Paku Bengkok", 50, "Tambahan duri pada tongkat kayu."),
            i(18, "Tembaga Mentah", 110, "Konduktor lemah untuk gear dasar."),
            i(19, "Sisa Roti Keras", 25, "Umpan monster atau ekstrak karbon."),
            i(20, "Tumbukan Arang", 60, "Filter air atau campuran mesiu."),
            i(21, "Serbuk Sari Gagal", 85, "Bahan pelapis racun level 1."),
            i(22, "Sisik Ular Darat", 120, "Bahan armor anti-gesek."),
            i(23, "Biji Besi Kasar", 130, "Material utama pedang standar."),
            i(24, "Air Hujan Asam", 95, "Pelarut material logam."),
            i(25, "Kulit Goblin", 115, "Armor ringan kelas bawah."),
            i(26, "Cakar Serigala Liar", 140, "Aksesoris penambah serangan fisik."),
            i(27, "Tali Usus", 90, "Tali busur lentur."),
            i(28, "Lendir Beracun", 150, "Ekstrak senjata racun durasi pendek."),
            i(29, "Batang Padi Besi", 125, "Tenunan tameng ringan."),
            i(30, "Tulang Belulang Orc", 160, "Pembuatan gada atau kapak tulang."),
            i(31, "Serat Kapas Sintetis", 105, "Bahan pakaian pelindung cuaca."),
            i(32, "Minyak Lemak Hewan", 100, "Pelumas engsel armor mekanik."),
            i(33, "Kerikil Tajam", 30, "Amunisi katapel."),
            i(34, "Spora Jamur Gua", 135, "Bahan peledak asap buta."),
            i(35, "Timah Hitam", 170, "Pelindung radiasi atau racun."),
            i(36, "Jaring Laba-Laba", 110, "Benang jahit luka atau zirah."),
            i(37, "Bulu Harpy Rontok", 145, "Fletching anak panah jarak jauh."),
            i(38, "Kantung Racun Kecil", 180, "Ekstrak Poison Damage."),
            i(39, "Tali Kawat Karat", 95, "Pengikat pelat dada armor."),
            i(40, "Pasir Silika", 120, "Pembuatan lensa kacamata goggles."),
            i(41, "Kristal Garam Kotor", 70, "Pengawet bahan makanan/organik."),
            i(42, "Serpihan Tembikar", 80, "Bahan dasar peledak fragmentasi."),
            i(43, "Ekstrak Lidah Buaya", 130, "Salep penyembuh luka bakar."),
            i(44, "Darah Monster", 195, "Katalis crafting sihir darah."),
            i(45, "Ekor Kalajengking", 210, "Mata tombak beracun."),
            i(46, "Kulit Katak Rawa", 140, "Bahan sepatu anti-air."),
            i(47, "Gigi Kelelawar", 90, "Tambahan kancing zirah."),
            i(48, "Lumut Bercahaya", 155, "Penerang helm peramban gua."),
            i(49, "Belerang Mentah", 165, "Bahan mesiu standar."),
            i(50, "Kertas Perkamen Kuno", 200, "Bahan pelapis buku mantra."),
            i(51, "Besi Tempa", 350, "Material standar armor prajurit."),
            i(52, "Kulit Beruang Coklat", 420, "Zirah kulit dengan pertahanan dingin."),
            i(53, "Kayu Mahoni Keras", 310, "Gagang pedang tahan lama."),
            i(54, "Kawat Tembaga", 290, "Komponen gear taktis ringan."),
            i(55, "Minyak Pelumas Taktis", 450, "Mempercepat reload senjata mekanik."),
            i(56, "Baja Ringan", 500, "Plat pelindung dada yang tidak berat."),
            i(57, "Lendir Asam", 480, "Pelarut kunci atau pelebur armor musuh."),
            i(58, "Serat Kain Anti-Robek", 380, "Pakaian dasar unit patroli."),
            i(59, "Kristal Air Murni", 600, "Crafting cincin regenerasi HP."),
            i(60, "Baja Karbon", 550, "Senjata dengan ketajaman tinggi."),
            i(61, "Taring Ogre", 580, "Material pembuat gada penghancur."),
            i(62, "Tulang Baja", 620, "Bingkai perisai menara (tower shield)."),
            i(63, "Sari Pati Tumbuhan", 400, "Meningkatkan efektivitas ramuan."),
            i(64, "Benang Sutra Laba-laba", 670, "Jubah penyihir kelas menengah."),
            i(65, "Biji Timah Putih", 390, "Pelapis anti-korosi pada senjata."),
            i(66, "Cangkang Kumbang", 530, "Pelindung bahu (pauldron)."),
            i(67, "Sisik Ikan Mutan", 560, "Zirah yang meningkatkan napas di air."),
            i(68, "Ekstrak Penisilin", 470, "Penawar racun tingkat menengah."),
            i(69, "Kaca Tahan Pecah", 490, "Lensa teropong bidik (scope)."),
            i(70, "Getah Karet Taktis", 440, "Peredam benturan di sepatu boots."),
            i(71, "Bulu Serigala Salju", 650, "Menahan efek beku dari cuaca ekstrim."),
            i(72, "Batu Api (Flint)", 320, "Pemantik proyektil senjata api."),
            i(73, "Kulit Buaya Rawa", 590, "Zirah tahan asam."),
            i(74, "Platina Mentah", 750, "Bahan dasar kalung penangkal sihir."),
            i(75, "Serbuk Mangan", 460, "Peningkat kekuatan tebasan pedang."),
            i(76, "Tanduk Banteng", 610, "Hiasan helm yang menambah Critical."),
            i(77, "Resin Mengkristal", 410, "Pengunci gagang dan bilah pedang."),
            i(78, "Serpihan Bintang", 800, "Bahan crafting jimat keberuntungan."),
            i(79, "Kain Katun Steril", 340, "Perban penyembuh tanpa risiko infeksi."),
            i(80, "Jarum Suntik Bekas", 300, "Proyektil dart beracun."),
            i(81, "Titanium Kasar", 880, "Bahan frame exoskeleton ringan."),
            i(82, "Cakar Gargoyle", 690, "Pisau lempar dengan elemen tanah."),
            i(83, "Madu Hutan Tersihir", 720, "Bahan ramuan pemulih stamina seketika."),
            i(84, "Sayap Kupu-Kupu Ilusi", 740, "Jubah yang meningkatkan Evasion."),
            i(85, "Baja Damaskus", 1500, "Pedang dengan pola yang tidak bisa patah."),
            i(86, "Sisik Naga Tanah", 2200, "Tameng dengan pertahanan fisik absolut."),
            i(87, "Inti Slime Mutasi", 1800, "Sumber tenaga baterai organik."),
            i(88, "Akar Pohon Kehidupan", 2500, "Tongkat sihir berelemen penyembuh."),
            i(89, "Darah Vampir", 2000, "Crafting pedang lifesteal."),
            i(90, "Kulit Troll Regenerasi", 2400, "Armor yang memulihkan HP perlahan."),
            i(91, "Kaca Pembesar Optik", 1600, "Sensor penemu titik lemah (weakpoint)."),
            i(92, "Serat Karbon Taktis", 1950, "Pakaian tempur ringan dan tahan peluru."),
            i(93, "Mithril Mentah", 3000, "Pelindung sihir kelas tinggi."),
            i(94, "Venom Gland Murni", 2100, "Pelapis racun pembunuh instan."),
            i(95, "Mata Harpy Ratu", 2300, "Crafting helm night vision organik."),
            i(96, "Bulu Griffon", 1750, "Sepatu bot yang meningkatkan lompatan."),
            i(97, "Ekstrak Adrenalin", 1850, "Stimulan untuk peningkatan Attack Speed."),
            i(98, "Batu Kuarsa Safir", 2600, "Penyimpan mana/energi cadangan."),
            i(99, "Kayu Besi Purba", 2150, "Gagang tombak yang tidak bisa dihancurkan."),
            i(100, "Jantung Mesin Karat", 3500, "Mengaktifkan golem atau drone pendamping."),
            i(101, "Pelat Paduan Enath", 2800, "Sisa material dari Organisasi Enath."),
            i(102, "Kain Seragam Enath", 2650, "Bahan rompi kamuflase militer elit."),
            i(103, "Sutra Laba-laba Gua", 2450, "Jubah anti-sihir tingkat tinggi."),
            i(104, "Cangkang Kura-Kura Batu", 2700, "Tameng punggung berat anti-serangan belakang."),
            i(105, "Kristal Elektromagnetik", 2900, "Bahan senjata pelumpuh (Stun)."),
            i(106, "Es Abadi", 3200, "Menempa pedang berelemen beku."),
            i(107, "Batu Bara Neraka", 3100, "Bahan bakar forge tungku legendaris."),
            i(108, "Getah Beracun Hydra", 3300, "Ramuan pelebur pertahanan musuh."),
            i(109, "Logam Orichalcum", 4000, "Armor berat dengan mobilitas ringan."),
            i(110, "Tali Serat Optik", 2200, "Mengikat komponen senjata energi."),
            i(111, "Lencana Black Owl (Rusak)", 2500, "Material untuk helm taktis elit."),
            i(112, "Kevlar Black Owl", 3400, "Pelindung dada anti-penetrasi tinggi."),
            i(113, "Kapsul Sterilisasi", 3000, "Membersihkan semua debuff saat dipasang ke armor."),
            i(114, "Taring Serigala Alpha", 2600, "Dagger ganda Armor Piercing."),
            i(115, "Sisik Ikan Leviathan", 3800, "Zirah kebal tekanan water."),
            i(116, "Darah Orc Warlord", 2950, "Ramuan peningkat Critical Damage."),
            i(117, "Tulang Sumsum Murni", 3600, "Katalis kebangkitan senjata mati."),
            i(118, "Air Mata Banshee", 2750, "Crafting perhiasan anti-Charm/Fear."),
            i(119, "Debu Bintang Jatuh", 4500, "Enchanment senjata Holy."),
            i(120, "Baterai Plasma", 4200, "Sumber daya pedang energi/laser."),
            i(121, "Inti Besi Enath", 8000, "Material inti crafting meriam railgun."),
            i(122, "Blueprint Medis Enath", 7500, "Resep crafting ramuan Full Restore."),
            i(123, "Visor Taktis Black Owl", 9000, "Kacamata penunjuk HP dan kelemahan musuh."),
            i(124, "Modul Senjata Black Owl", 9500, "Upgrade untuk mengurangi cooldown skill."),
            i(125, "Plat Baja Vallesia", 8500, "Plat baja agraris yang sangat tebal."),
            i(126, "Sirkuit Agrar Vallesia", 10000, "Peningkat efisiensi healing item 200%."),
            i(127, "Tanduk Minotaur Greed", 11000, "Kapak raksasa penghancur tanah."),
            i(128, "Jantung Golem Pasir", 10500, "Zirah yang menyerap serangan tipe fisik."),
            i(129, "Taring Naga Kuno", 13000, "Mata tombak penembus sisik naga."),
            i(130, "Darah Murni Phoenix", 15000, "Crafting item Revive."),
            i(131, "Sayap Malaikat Jatuh", 14000, "Jubah yang memberikan kemampuan terbang sementara."),
            i(132, "Adamantium Murni", 18000, "Logam terkuat untuk tulang exoskeleton."),
            i(133, "Berlian Hitam", 16500, "Permata penguat Kekuatan serangan tertinggi."),
            i(134, "Batu Delima Darah", 12000, "Crafting cincin Vampiric level maksimal."),
            i(135, "Tali Busur Cahaya", 11500, "Menembakkan panah tanpa amunisi fisik."),
            i(136, "Ekstrak Racun Mutlak", 12500, "Penawar segala penyakit pandemik."),
            i(137, "Otak Mutan Cerdas", 13500, "Cincin peningkat Intelligence drastis."),
            i(138, "Kulit Chimera", 14500, "Armor dengan resistensi semua elemen sihir."),
            i(139, "Tulang Rusuk Lich", 15500, "Tongkat sihir Necromancy."),
            i(140, "Serum Mutasi Genetik", 20000, "Upgrade base stats karakter secara permanen."),
            i(141, "Cakar Behemoth", 13000, "Gauntlet pemukul berdaya ledak."),
            i(142, "Mata Badai", 14000, "Inti tongkat pengendali cuaca."),
            i(143, "Obsidian Cair", 11000, "Pelapis pedang tahan lava."),
            i(144, "Logam Meteorit", 17000, "Material senjata luar angkasa."),
            i(145, "Benang Emas Murni", 12500, "Pengikat permata pada tongkat legendaris."),
            i(146, "Kayu Pohon Yggdrasil", 19000, "Tongkat sihir pemulih massal."),
            i(147, "Lendir Emas Raja Slime", 13000, "Bahan pelapis armor anti-Stun."),
            i(148, "Inti Reaktor Mikro", 22000, "Penyuplai energi tanpa batas untuk gear."),
            i(149, "Sisik Ratu Harpy", 11500, "Pelindung angin kencang (Tornado)."),
            i(150, "Kristal Jiwa Kosong", 16000, "Menyerap jiwa boss untuk enchant senjata."),
            i(151, "Kristal Elektrik", 9500, "Peningkat serangan bertipe Lightning."),
            i(152, "Getah Pohon Beracun", 8500, "Pembuatan jebakan area (AoE trap)."),
            i(153, "Serat Kaca Anti Peluru", 10000, "Rompi anti-serangan balistik."),
            i(154, "Biji Besi Magnetik", 10500, "Sarung tangan penarik senjata musuh."),
            i(155, "Bubuk Tulang Naga", 12000, "Obat kuat peningkat ketahanan fisik."),
            i(156, "Daun Teratai Salju", 11000, "Pemulih status Burn permanen."),
            i(157, "Sayap Kelelawar Raksasa", 9000, "Glider parasut taktis."),
            i(158, "Lendir Cacing Tanah", 9500, "Pelumas regenerasi armor otomatis."),
            i(159, "Kaca Prismatik", 13000, "Perisai reflektor sihir."),
            i(160, "Batu Apung Vulkanik", 10000, "Pembuatan granat bakar tingkat tinggi."),
            i(161, "Inti Api Elemental", 11500, "Penambah damage api pada Basic Attack."),
            i(162, "Logam Antimateri", 25000, "Material pedang pembelah ruang."),
            i(163, "Kristal Waktu", 24000, "Aksesoris pengurang Cooldown absolut."),
            i(164, "Darah Raja Iblis", 18000, "Peningkat Kekuatan dengan mengorbankan HP."),
            i(165, "Bulu Burung Owl Mistis", 10500, "Peningkat akurasi senjata api jarak jauh."),
            i(166, "Cangkang Penyu Purba", 21000, "Tameng pelindung dari kehancuran total."),
            i(167, "Akar Ginseng Emas", 20000, "Item peningkat Max HP permanen."),
            i(168, "Batu Loncatan Dimensi", 23000, "Sepatu bot Blink / Teleport."),
            i(169, "Air Mata Dewi", 26000, "Material crafting Holy Grail."),
            i(170, "Serpihan Inti Bumi", 15000, "Peningkat defense pertahanan berat."),
            i(171, "Tengkorak Panglima Perang", 14000, "Helm dengan aura intimidasi (Fear)."),
            i(172, "Baja Paduan Kosmik", 27000, "Material end-game kelas tinggi."),
            i(173, "Kawat Nano Taktis", 13500, "Tali pembunuh tak kasat mata."),
            i(174, "Jantung Mesin Waktu", 30000, "Membatalkan kematian 1 kali per tempur."),
            i(175, "Kristal Gravitasi", 16000, "Senjata pengubah bobot target."),
            i(176, "Serat Karbon Berlian", 25000, "Zirah teringan namun paling keras."),
            i(177, "Esensi Bayangan", 18000, "Peningkat Stealth / Invisibility."),
            i(178, "Logam Bio-Mekanik", 22000, "Armor yang menyatu dengan jaringan otot."),
            i(179, "Inti Plasma Matahari", 28000, "Crafting meriam penghancur kota."),
            i(180, "Batu Bertuah", 35000, "Mengubah logam biasa menjadi emas/koin."),
            i(181, "Baja Sintetis Vallesia", 75000, "Logam fusi agraris-militer, tidak bisa hancur."),
            i(182, "Data Inti Enath", 80000, "Membuka cetak biru seluruh Legendary Gear."),
            i(183, "Emblem Black Owl Murni", 65000, "Aksesoris yang memaksimalkan akurasi taktis."),
            i(184, "Pecahan Hologram Enath", 70000, "Crafting jubah penyamar optik 100%."),
            i(185, "Biji Bibit Vallesia Kuno", 85000, "Inti aksesoris yang memberikan regenerasi HP konstan."),
            i(186, "Inti Reaktor Black Owl", 90000, "Tenaga penggerak Exoskeleton Suit penuh."),
            i(187, "Serpihan Relik Vallesia", 95000, "Katalis penempaan senjata tingkat dewa."),
            i(188, "Protokol Medis Enath", 82000, "Modul zirah yang mencegah segala debuff kesehatan."),
            i(189, "Laras Taktis Black Owl", 88000, "Modul senjata api Damage dan penetrasi maksimal."),
            i(190, "Jubah Usang Commander", 60000, "Menurunkan moral dan stat Defense musuh di sekitar."),
            i(191, "Pangkat Bintang Commander", 100000, "Menyematkan pasif kebal terhadap serangan fatal."),
            i(192, "Inti Komando Taktis", 72000, "Sinkronisasi skill dengan rekan satu party."),
            i(193, "Esensi Biologis Mutakhir", 120000, "Penawar kelaparan dan penyakit abadi (SDG 2 & 3)."),
            i(194, "Ekstrak Tubuh Nirlelah", 150000, "Material upgrade fisik pamungkas; stamina menjadi tak terbatas."),
            i(195, "Fragmen Tubuh Nirlelah", 140000, "Implan biomekanik untuk mengunci HP agar tidak turun di bawah 1%."),
            i(196, "Kristal Evolusi Fisik", 130000, "Mengaktifkan mode Tubuh Nirlelah pada karakter."),
            i(197, "Batu Permata Kekuatan", 110000, "Pengali ganda (multiplier) status Kekuatan tempur."),
            i(198, "Inti Ekstraksi Kekuatan", 115000, "Mengubah 100% Defense musuh menjadi Kekuatan tambahan karakter."),
            i(199, "Simbol Absolut Kekuatan", 200000, "Rune sakti peningkat output damage tanpa batas."),
            i(200, "Jantung Avatar Pandemi", 250000, "Inti pedang pembasmi yang mampu menyembuhkan dunia."),
            i(201, "Iron Ore", 300, "Bijih dasar untuk penempaan equipment level awal."),
            i(202, "Copper Ore", 350, "Bijih tembaga untuk upgrade peralatan ringan."),
            i(203, "Tin Ore", 400, "Bijih timah untuk penempaan komponen menengah."),
            i(204, "Silver Ore", 500, "Bijih perak untuk perlengkapan dengan kualitas lebih baik."),
            i(205, "Gold Ore", 650, "Bijih emas untuk upgrade equipment bernilai tinggi."),
            i(206, "Mithril Ore", 900, "Bijih mithril untuk equipment kelas menengah-atas."),
            i(207, "Orichalcum Ore", 1200, "Bijih orichalcum untuk penempaan lanjutan."),
            i(208, "Adamantite Ore", 1600, "Bijih adamantite untuk equipment sangat kuat."),
            i(209, "Celestite Ore", 2000, "Bijih celestite dengan energi langit yang stabil."),
            i(210, "Dragonite Ore", 2500, "Bijih dragonite untuk upgrade forge level tertinggi."),
    };

    private static final HashMap<Integer, Item> INGREDIENT_MAP = initializeMap();

    private static HashMap<Integer, Item> initializeMap() {
        HashMap<Integer, Item> map = new HashMap<>();
        for (Inqredients ingredient : DUMMY_INGREDIENTS) {
            map.put(ingredient.getIdItem(), ingredient);
        }
        return map;
    }

    private static Inqredients i(int id, String nama, int hargaJual, String deskripsi) {
        return new Inqredients(id, nama, hargaJual, deskripsi, itemType.INQREDIENT);
    }

    public static List<Inqredients> getDummyIngredients() {
        return List.of(DUMMY_INGREDIENTS);
    }

    public static HashMap<Integer, Item> getDummyIngredientsMap() {
        return INGREDIENT_MAP;
    }
}
